### ISSUE TITLE
Not supported for different VS Code version

### ISSUE THREAD

**Issue by veerpatil** [mudit94/cypress-gitlab-template-vscode#1]
I am trying to install it on VS code 1.77.3 getting following error. 

![image](https://github.com/mudit94/cypress-gitlab-template-vscode/assets/35873990/b2a9eebb-1abb-4dce-942e-ef7f184e637c)

**Comment by mudit94** [comment]
@veerpatil , request you to update to 1.79.2 version .

**Comment by veerpatil** [comment]
Thanks @mudit94
